Algoritmo "laco_for"
// Disciplina   : [Logica de Programacao com JavaScript]
// Professor   : Jailson Costa dos Santos
// Descrição   : Faz o laco de repeticao com o comando "para"
// Autor(a)    : Maria Eduarda de Sales Miranda
// Data atual  : 04/04/2024
Var
contador: inteiro


Inicio
para contador de 1 ate 10 passo 1 faca
     Escreval("Professor Jailson")
fimpara


Fimalgoritmo