Algoritmo "Laco_repeticao"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Jailson Costa dos Santos
// Descrição   : Enquanto o valor do contador (inicialmente 0) for menor do que 8, o nome digitado se repetirá
// Autor(a)    : Maria Eduarda de Sales Miranda
// Data atual  : 27/03/2024
Var
contador: inteiro


Inicio
enquanto contador < 8 faça
Escreval("Jailson")
contador<- contador+1
fimenquanto

Fimalgoritmo