Algoritmo "Menor_Maior_que10"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Jailson Costa dos Santos
// Descrição   : Informa se o número digitado é maior ou menor que 10
// Autor(a)    : Maria Eduarda de Sales Miranda
// Data atual  : 25/03/2024
Var
num: inteiro


Inicio
Escreval("Digite um número")
leia(num)
se (num > 10) então
Escreval("É MAIOR QUE 10!")
senão
Escreval("É MENOR QUE 10!")
Fimse
Fimalgoritmo