Algoritmo "multiplicacao_para"
// Disciplina   : [Logica de Programacao com JavaScript]
// Professor   : Jailson Costa dos Santos
// Descrição   : criacao de um laco de repeticao de tabuada
// Autor(a)    : Maria Eduarda de Sales Miranda
// Data atual  : 04/04/2024
Var
contadora,numero: inteiro

Inicio
Escreval("Digite um numero")
leia(numero)
Escreval("")
para contadora de 1 ate 10 passo 1 faca
     Escreval(numero," X",contadora," =", contadora*numero)
fimpara

Fimalgoritmo