Algoritmo "positivo_negativo"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Jailson Costa dos Santos
// Descrição   : Determina se o número digitado é positivo ou negativo
// Autor(a)    : Maria Eduarda de Sales Miranda
// Data atual  : 26/03/2024
Var
num: inteiro


Inicio
Escreval("Digite um valor")
Leia(num)
se  num >= 0 então
Escreval("Esse número é positivo")
senão
Escreval("Esse número é negativo")
Fimse
Fimalgoritmo