Algoritmo "Quadrados_dos_numeros"
// Disciplina   :[Lógica de Programação com JavaScript]
// Professor   : Jailson Costa dos Santos
// Descrição   : Apresentar os quadrados dos números inteiros de 15 a 200
// Autor(a)    : Maria Eduarda de Sales Miranda
// Data atual  : 03/04/2024
Var
numero:inteiro


Inicio
numero<- 15
repita
Escreval(numero * numero)
numero <- numero + 1
até numero > 200


Fimalgoritmo